baseURL = "https://onestla.tech/"
defaultContentLanguage = "fr"
languageCode = "fr-fr"
title = "âœŠ onestla.tech"
theme = "beautifulhugo"
sectionPagesMenu = "main"

[Params]
  socialShare = false
  organizationName = "onestla.tech"
  favicon = "avatar.png"
  logo = "avatar.png"

  [markup.goldmark.renderer]
  unsafe = true
